# This is a basic workflow to help you get started with Actions

name: C_CI

# Controls when the workflow will run
on:
  push:
    branches: "main"
  pull_request:
    branches: "main"


jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Build project
      uses: nicledomaS/cmake_build_action@v1.4
      with:
        submodule_update: ON
        run_tests: ON
        unit_test_build: -Dtest=ON
        

   
